---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yesuhuangsi.
--- DateTime: 2020-03-10 22:31
---

local common = require "common"

local ip = ngx.re.match(common.get_ip(),"[0-9]+.[0-9]+.[0-9]+.([0-9]+)")
local id = ngx.re.match(ngx.var.sub_path, "([0-9]+)(.*)")

if id then
    if ip[1] ~= id[1] then
        ngx.exit(ngx.HTTP_BAD_REQUEST)
    end
end
