---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yesuhuangsi.
--- DateTime: 2020-03-10 22:00
---

local _M = { _VERSION = '0.10' }

function _M.get_ip()
    local ip = ngx.var.http_x_real_ip or ngx.var.http_x_forwarded_for or ngx.var.remote_addr or "0.0.0.0"
    return ip
end

function _M.mkdir(path)
    local dir = io.open(path, "w+")
    if not dir then
        os.execute("mkdir -p " .. path)
    else
        dir:close()
    end
end

return _M
